config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/tagged', to: "pages#tagged", as: :tagged
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index, :new, :create, :update]
  resources :projects, only: [:new, :create, :show, :index] do
    resources :matches, only: [:create]
  end
  resources :matches, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

# hello

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :matches
  validates :name, presence: true
  acts_as_taggable_on :tags
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :matches
  has_many :projects
  acts_as_taggable_on :tags

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: [:index,:show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :bio, tag_list: []])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def create
    @match = Match.new(match_params)
    @match.user = current_user
    authorize @match
    if @match.save
      redirect_to user_path(current_user)
    else
      @project = @match.project
      render 'projects/show'
    end
  end

  def update
    @match = Match.find(params[:id])
    @match.update(match_params)
    authorize @match
    if @match.save
      redirect_to user_path(current_user)
    else
      @project = @match.project
      render 'users/show'
    end
  end

private

  def match_params
    params.require(:match).permit(:project_id, :role, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :tagged]

  def home
    @projects = Project.last(6).reverse!
  end

  def tagged
    if params[:tag].present?
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.all
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :query]
  def show
    @project = Project.find(params[:id])
    @matches = @project.matches
    @match = Match.new
  end


  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @projects = policy_scope(Project).where(sql_query, query: "%#{params[:query]}%")
    else
      @projects = policy_scope(Project).all.order(created_at: :desc)
    end
  end

  def new
    @project = Project.new
    authorize @project
  end

  def tagged
  if params[:tag].present?
    @projects = Project.tagged_with(params[:tag])
  else
    @projects = Project.all
  end
end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :photo, tag_list: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #   @users = policy_scope(User).all.order(created_at: :desc)
  # end

  def show
    @user = User.find(params[:id])
    @projects = Project.where(user: @user)
    @matches = Match.where(user: @user)
  end

   # def tagged
   #    if params[:tag].present?
   #      @users = User.tagged_with(params[:tag])
   #    else
   #      @users = User.all
   #    end
   # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_bio.html.erb
<h1>Edit Your Bio</h1>
<%= simple_form_for(@user) do |f| %>
    <%= f.input :bio %>
    <%= f.submit "Submit" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevTavern</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="top-banner">
<h1 class="title-text">DEV-TAVERN</h1>
</div>

app/views/pages/home.html.erb
<%= render '/shared/banner' %>
<div class="card-container">
  <div class="container">

    <div class="search-font"><h1>Find awesome projects to work on now</h1></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= form_tag projects_path, class: "row", method: :get do %>
          <div class="col-12 col-sm pr-sm-0">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control input-lg",
              id: "typed-text" %>
          </div>
          <div class="input-group-btn ml-3">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="cards mb-1">
      <% @projects.each do |project| %>
        <div class="card-background">
          <a href="<%= project_path(project) %>" class="card">
            <%= render 'projects/card', project: project %>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# if policy(Project).create? %>
  <%#= link_to "New project", new_project_path %>
<%# end %>

app/views/pages/tagged.html.erb
<%= render '/shared/banner' %>
<div class="card-container">
  <div class="container">

    <div class="search-font"><h1>Find awesome projects to work on now</h1></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= form_tag projects_path, class: "row", method: :get do %>
          <div class="col-12 col-sm pr-sm-0">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control input-lg",
              placeholder: "Find a Project" %>
          </div>
          <div class="input-group-btn ml-3">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="cards mb-1">
      <% @projects.each do |project| %>
        <div class="card-background">
          <a href="<%= project_path(project) %>" class="card">
            <%= render 'projects/card', project: project %>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# if policy(Project).create? %>
  <%#= link_to "New project", new_project_path %>
<%# end %>

app/views/projects/_banner.html.erb
<% project = Project.find(params[:id]) %>
<div class="banner-project">
  <h1><%= project.name %></h1>
</div>

app/views/projects/_card.html.erb
<% if project.photo.attached? %>
  <%= cl_image_tag project.photo.key, class: "card-img", width: 300, height: 200, crop: :scale %>
<% else %>
  <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg", class: "card-img" %>
<% end %>

<div class="card-title">
  <h2><%= project.name %></h2>
  <h6><%= project.user.username %></h6>
</div>
<div class="looking-for">Looking for:</div>

<!-- TAGS -->
  <object >
    <div class='tag'>
      <% if project.tag_list.size <= 2 %>
        <% project.tag_list.each do |tag| %>
          <i class="fab fa-slack-hash", id='tag-icon'>
          <%= link_to tag, tagged_path(tag: tag), class: 'btn-tag' %>
          </i>
        <% end %>
      <% else %>
        <% project.tag_list.first(2).each do |tag| %>
          <i class="fab fa-slack-hash", id='tag-icon'>
            <%= link_to tag, tagged_path(tag: tag), class: 'btn-tag' %>
          </i>
        <% end %>
      </div>
        <div class="and-more">
      <%= link_to "And others", project_path(project), class: 'btn-tag' %>
      </div>
      <% end %>
    </div>
  </object>

app/views/projects/index.html.erb
<%= render '/shared/banner' %>
<div class="card-container">
  <div class="container">

    <div class="search-font"><h1>Find awesome projects to work on now</h1></div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= form_tag projects_path, class: "row", method: :get do %>
          <div class="col-12 col-sm pr-sm-0">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control input-lg",
              placeholder: "Find a Project" %>
          </div>
          <div class="input-group-btn ml-3">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  <div class="cards">
    <% @projects.each do |project| %>
    <div class="card-background">
      <%#= link_to project_path(project), class: "card" do  %>
      <a href="<%= project_path(project) %>" class="card">
        <%= render 'projects/card', project: project %>
      </a>
    </div>
  <% end %>
  </div>
</div>
</div>

app/views/projects/new.html.erb
<div class="container d-flex justify-content-around">
  <div class="card new-project-card p-3 mb-4 mt-4">
<h1>Create a New Project</h1>
<%= simple_form_for(@project) do |f| %>
    <span class="form-name"><%= f.input :name, label: "Project Name" %></span>
    <span class="form-description"><%= f.label :name, "Example: Moonshot - A Unity Adventure Game" %></span>
    <span class="form-name"><%= f.input :description, required: true, label: "Project Details", :input_html => {:rows => 10} %></span>
    <span class="form-description"><%= f.label :description, "A detailed description of your project's content, goals, and who you wish to recruit." %></span>
    <span class="form-name"><%= f.input :photo, as: :file, required: true %></span>
    <span class="form-name"><%= f.label :tag_list, "What kind of developer do you need?" %></span>

<%= f.input :tag_list, label: false, collection: [ "Unity 2D Developer", "Unity 3D Developer", "Game Programmer", "2D Graphic Designer", "3D Graphic Designer", "Sound Designer", "Musician", "Script Writer", "Level Designer", "Unreal Engine Developer" ], input_html: {class: "select2", multiple: "multiple", style: 'width: 655px'} %>



    <div class="d-flex justify-content-around"><%= f.submit "Create a new project", class: "btn btn-primary" %></div>


  <% end %>
</div>

</div>

app/views/projects/show.html.erb
<!-- Banner -->
    <%= render 'banner'%>
  </div>
<div class="container project-container">
<!-- Whole project info div -->
  <div class="project-info">

<!-- Project name, description and images -->
        <div class="project-profile-card">
        <div class="project-name pb-3">
          <h2 style="display: inline;"><%= @project.name %></h2>
        </div>

        <div class="description pb-3">
          <p><%= @project.description %></p>
        </div>

        <div class="images-div row justify-content-center">
          <% if @project.photo.attached? %>
          <div class="img-div">
            <%= cl_image_tag @project.photo.key, height: 400, width: 500, crop: :fill %>
          </div>
          <% end %>
        </div>
        </div>

<!-- Mebmer info and roles looking for -->
    <div class="members-bar">
        <div class="card project-profile-card">
        <h4><strong>Looking for</strong></h4>
        <ul class="skills">
          <% @project.tag_list.each do |tag| %>
              <li>
              <i class="fas fa-robot"></i>
               <%= tag %>
              </li>
          <% end %>
        </ul>
      </div>
      <div class="card project-profile-card">
        <h4><strong>Members</strong></h4>
        <div class="members">

          <!-- Link to the creator -->
          <%= link_to @project.user.username, user_path(@project.user), class: "member-link" %>

          <!-- Find other members and create link to their page -->
          <% @project.matches.each do |match| %>
            <% if match.status == "accepted" && match.user.username != @project.user.username %>
              <div>
                <%= link_to match.user.username, user_path(@project.user), class: "member-link" %>
              </div>
            <% end %>
          <% end %>

        </div>
        <% unless @project.user == current_user  %>
          <div class="buttons mt-3">
            <%= simple_form_for [@project, @match] do |f| %>
              <%= f.input :project_id, as: :hidden, input_html: { value: @project.id } %>
              <%= f.input :role, collection: @project.tag_list, include_blank: false %>
              <div class="d-flex justify-content-around"><%= f.submit 'Join our team', class: "btn btn-primary" %></div>
            <% end %>
          </div>
        <% end %>
      </div>
      </div>
    </div>

  </div>
</div>
</div>

app/views/shared/_banner.html.erb
<div class="top-banner">
<h1 class="title-text">DEV-TAVERN</h1>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "dtlogofriday.png", alt: "logo" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= link_to "Create Project", new_project_path, class: "nav-link navbutton" %>
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/gvholley", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Settings", "/users/edit", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="cards">
    <% @users.each do |user| %>
    <div class="card-background">
      <%#= link_to project_path(project), class: "card" do  %>
      <a href="<%= user_path(user.username) %>" class="card">
        <%= render 'card', user: user %>
      </a>
    </div>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-banner">
  <div class="container">
    <div class="user-info">
      <h1><%= @user.username %></h1>
      <h3><%= @user.tag_list %></h3>
    </div>
  </div>
</div>
<div class="container user-project-container">
<p><%= @user.bio %></p>
</div>
<% if @user == current_user %>
  <div class="container user-project-container">
    <div class="container-user-title">
      <h1><%= @user.username %>'s requests</h1>
    </div>
    <% if @matches.any? %>
    <% @matches.each do |match| %>
    <div class="project">
      <div class="project-detail">
        <h2><%= link_to match.project.name, project_path(match.project) %></h2>
      </div>
  　　 <div class="project-status">
         <div>
           <i class="fab fa-slack-hash">
             <%= link_to match.role, tagged_path %>
           </i>
          </div>
           <%= match.status %>
       </div>
      </div>
     <% end %>
    <% else %>
      <div class="m-3">
        <h3>You haven't requested yet...</h3>
      </div>
    <% end %>
  </div>
<% end %>
<div class="container container-user-title">
    <h1>
      <%= @user.username %>'s projects
    </h1>
</div>
<div class="container user-project-container">
  <% @projects.each do |project| %>
    <div class="project">
      <div class="project-detail">
        <h2><%= link_to project.name, project_path(project) %></h2>
        <%= project.description %>
      </div>
      <div class="project-status request-status">
        <% if @user == current_user %>
          <button class="btn btn-primary edit-btn btn-status">Check requests</button>
          <div class="edit-form">
            <% project.matches.each do |match| %>
            <% if match.status == "Pending..." %>
                <div class="requested-user">
                <small>From</small>
                <h5><%= link_to match.user.username, user_path(match.user)  %></h5>
                </div>
                <small><%= match.role %></small>
                <div class="status">
                <%= simple_form_for match do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'accepted' }  %>
                  <%= f.submit 'accept', class: 'btn btn-sm btn-primary btn-status' %>
                <% end %>
                <%= simple_form_for match do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'rejected' }  %>
                  <%= f.submit 'reject', class: 'btn btn-sm btn-primary btn-status' %>
                <% end %>
                </div>
              <% end %>
          <% end %>
          </div>
        <% else %>
          <% project.tag_list.each do |tag| %>
             <i class="fab fa-slack-hash">
               <%= link_to tag, tagged_path %>
             </i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>